// Autogenerated from Pigeon (v9.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by WeatherApi.
NSObject<FlutterMessageCodec> *WeatherApiGetCodec(void);

@protocol WeatherApi
- (void)getWeatherByCityNameCityName:(NSString *)cityName completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void WeatherApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WeatherApi> *_Nullable api);

NS_ASSUME_NONNULL_END
