// Autogenerated from Pigeon (v9.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoInfo (
  val title: String? = null,
  val length: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VideoInfo {
      val title = list[0] as String?
      val length = list[1] as Double?
      return VideoInfo(title, length)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      title,
      length,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Video (
  val videoInfo: VideoInfo? = null,
  val bytes: ByteArray? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): Video {
      val videoInfo: VideoInfo? = (list[0] as List<Any?>?)?.let {
        VideoInfo.fromList(it)
      }
      val bytes = list[1] as ByteArray?
      return Video(videoInfo, bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      videoInfo?.toList(),
      bytes,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object VideoApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Video.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Video -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is VideoInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VideoApi {
  fun sendVideoFromNative(): Video

  companion object {
    /** The codec used by VideoApi. */
    val codec: MessageCodec<Any?> by lazy {
      VideoApiCodec
    }
    /** Sets up an instance of `VideoApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.VideoApi.sendVideoFromNative", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.sendVideoFromNative())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
